# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# setup
sass:
  style: compressed

exclude: [Gemfile, Gemfile.lock, README.md]

# Site settings
title: 10k apart
email: disjfa@disjfa.nl
description: > # this means to ignore newlines until "baseurl:"
  Project for the 10k apart competition, uses some simple examples to make the internet cool again.
baseurl: "/10k-2016" # the subpath of your site, e.g. /blog
url: "https://disjfa.github.io" # the base hostname & protocol for your site
github_username:  disjfa

# Build settings
markdown: kramdown

# serve
port:    4000
host:    0.0.0.0
